service: agroenv-search-api
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1
  apiGateway:
    shouldStartNameWithService: true
  endpointType: REGIONAL
  environment:
    NARO_AGROENV_STATIC_API_ENDPOINT: ${env:NARO_AGROENV_STATIC_API_ENDPOINT}

package:
  exclude:
    - __tests__
    - .*
    - dist/lib
    - docs/
    - src/
    - eslintrc.js
    - package.json
    - prettierrc
    - README.md
    - serverless.yml
    - tsconfig.eslint.json
    - tsconfig.json
    - "*.log"
    - yarn.lock
    - package-lock.json
    - webpcak.config.js

functions:
  search:
    handler: dist/search.handler
    events:
      - http:
          path: '/search'
          method: get
          integration: lambda-proxy
