service: agroenv-search-api
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-northeast-1
  apiGateway:
    shouldStartNameWithService: true
  endpointType: REGIONAL
  environment:
    FOO: BAR

package:
  exclude:
    - __tests__
    - .*
    - bin/
    - docs/
    - src/
    - package.json
    - README.md
    - serverless.yml
    - tsconfig.json
    - yarn.lock
    - package-lock.json

functions:

  describe:
    handler: dist/describe.handler
    events:
      - http:
          path: '/'
          method: get
          integration: lambda-proxy

  search:
    handler: dist/search.handler
    events:
      - http:
          path: '/search'
          method: get
          integration: lambda-proxy
